### PR TITLE
Add STUN list on android

### PR DESCRIPTION
**Pull request by cmendes0101**
Add stun list to the endpoint server configuration.

endpoint.start({
    service: {
        stun: ['stun.l.google.com:19302','stun4.l.google.com:19302'],
    },
})

### CODE REVIEW

**Comment by datso** [comment]
Thanks for the PR, will you make a PR for the iOS version ?

**Comment by datso** [comment]
Is it possible also to have bindings to change STUN settings when service already started ?

**Comment by cmendes0101** [comment]
I took a look at iOS but wasn't too sure how to go about it. I know Android but not so much iOS. I'll take a look again later on to see if I can get that in.

Is PJSIP capable of changing just STUN settings after starting? I haven't tried that before and thought it was a restart of the service. I'll take a look to see what i can find. If you have any example's I can definitely drop that in.

**Comment by rcidt** [comment]
@datso @cmendes0101 any news on this? I am also trying to implement this for iOS but am having a really rough time.

**Comment by rcorrie** [comment]
@datso @cmendes0101 check out my PR, let me know your thoughts please

**Pull request merged**
