### PR TITLE
Bug Fix : mute function does not work

### PR DESCRIPTION
**Pull request by rcorrie**
https://github.com/datso/react-native-pjsip/issues/56

### CODE REVIEW

**Comment by rcorrie** [comment]
@datso that merge conflict is trivial, that file should be removed from source control

**Comment by datso** [comment]
Thanks for the PR, is it possible to rebase form master and remove any changes except
- android/src/main/java/com/carusto/ReactNativePjSip/PjSipCall.java
- ios/RTCPjSip/PjSipCall.m

**Comment by rcorrie** [comment]
@datso ok, no more conflicts.

I would suggest to update the gitignore though. You have a lot of IDE preference files checked in.

**Comment by veenedu** [comment]
Mute on IOS is still not working

**Pull request merged**
