### PR TITLE
Adds codec object to settings object

### PR DESCRIPTION
**Pull request by rcorrie**
Implements this feature:

```javascript
let endpoint = new Endpoint();
let state = await endpoint.start();
let {accounts, calls, settings, connectivity} = state;

console.log("codecs", settings.codecs); // Shows a list of available codecs with priority
```

### CODE REVIEW

**Comment by rcorrie** [comment]
@datso any plans on merging this in?

**Comment by datso** [comment]
Hi, I'm going to rewrite a little bit your code, and I cant merge this without the iOS implementation.

**Comment by rcorrie** [comment]
@datso I believe the iOS implementation is there already (you wrote it), it was just missing the android implementation, which is this PR.

**Comment by datso** [comment]
Ok I'll merge this, thanks btw for the PR.

**Pull request merged**
